version: '3'
services:
  ts-node-base:
    # Path to dockerfile.
    build: 
      context: .
      dockerfile: Dockerfile
      target: base
    env_file:
      - .env
    # Mapping of container port to host
    expose:
      - '3000'
    ports:
      - '3000:3000'
    # Mount volume 
    volumes:
      - ./src:/usr/src/app/src
      - ./nodemon.json:/usr/src/app/nodemon.json
    command: npm run dev